### ISSUE TITLE
[Solved] Is it compatible with SEOmatic ?

### ISSUE THREAD

**Issue by LouisCuvelier** [alpshq/craft-share-previews#1]
Hi,
 I've interest in the plugin but I'm using SEOmatic. Is Share Previews compatible with SEOmatic ?

**Comment by jakubjo** [comment]
Hi! Sorry for my late reply, GitHub did not sent issue notifications.

I'll look into it later today and post an update here. I assume there shouldn't be any major problem.

**Comment by jakubjo** [comment]
Hi Louis!

To integrate the plugin with SEOMatic you only need to use the generated image URLs from the plugin.

Add `{entry.getSharePreviewUrl()}` to your desired SEO image source settings inside of SEOMatic.

I've attached you a screenshot.

I'll keep this issue offen, as I'll incorporate this in the documentation.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/2873852/125279789-a3175b00-e314-11eb-891d-9b1f190b318e.png">
