### ISSUE TITLE
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by stigzelm** [alpshq/craft-share-previews#10]
Cannot install this plugin, getting the following error in install.

ParseError
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

<img width="1680" alt="Screenshot 2022-03-01 at 22 04 23" src="https://user-images.githubusercontent.com/703669/156240764-43230495-7186-4ade-98fb-901514724880.png">

Craft version: 3.7.34
Share previews version: 1.7.1
PHP verson: 7.3.3

**Comment by stigzelm** [comment]
Got it working with php@7.4...

**Comment by jakubjo** [comment]
Thanks for pointing that out. I'll add PHP 7.4 as a requirement in `composer.json`.
