### ISSUE TITLE
Editing actions are not functioning

### ISSUE THREAD

**Issue by andypullen** [alpshq/craft-share-previews#14]
Functions like adding, moving, or deleting layers, the cancel and save buttons, etc. are not working with Craft 4.3.5. I can find no logged errors either in Craft's logs or in the dev console.

**Comment by jakubjo** [comment]
I'm looking into it, @andypullen!

**Comment by jakubjo** [comment]
Thanks for reporting, @andypullen.
The issue was related to Chrome and was fixed in https://github.com/alpshq/craft-share-previews/commit/0bdbf404ae7b9e2521cda6ddf452edda55df34ba.
