### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by skoften** [alpshq/craft-share-previews#2]
Getting an error when trying to install the package;

```
Using version ^1.1 for alpshq/craft-share-previews
./composer.json has been updated
Running composer update alpshq/craft-share-previews
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - alpshq/craft-share-previews[v1.1.0, ..., v1.1.2] require illuminate/collections ^8.0.0 -> satisfiable by illuminate/collections[v8.0.0, ..., 8.x-dev].
    - illuminate/collections[v8.0.0, ..., 8.x-dev] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but the package is fixed to v7.30.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires alpshq/craft-share-previews ^1.1 -> satisfiable by alpshq/craft-share-previews[v1.1.0, v1.1.1, v1.1.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Also tried via CP;

![Screenshot 2021-06-25 at 10 09 30](https://user-images.githubusercontent.com/1286410/123392542-771e7a80-d59d-11eb-9386-300c0ea93e87.jpg)

Running Craft Pro 3.6.17

**Comment by jakubjo** [comment]
Hi! Sorry for my late reply, GitHub did not sent issue notifications.

Would you be willing to share your composer.json & your PHP version? 
You can send it directly to jakub@jakub.io if you don't want to publicly share it.

The plugin uses the illuminate/collection package. There seems to be a dependency issue.

**Comment by skoften** [comment]
Hi Jakub,

Attached my composer.json.

Running PHP 7.4.12.

Thanks!

Arjan Brinkman



From: Jakub Jo ***@***.***>
Reply to: alpshq/craft-share-previews ***@***.***>
Date: Wednesday, 7 July 2021 at 15:06
To: alpshq/craft-share-previews ***@***.***>
Cc: "Skoften.net" ***@***.***>, Author ***@***.***>
Subject: Re: [alpshq/craft-share-previews] Issue installing (#2)


Hi! Sorry for my late reply, GitHub did not sent issue notifications.

Would you be willing to share your composer.json & your PHP version?
You can send it directly to ***@***.******@***.***> if you don't want to publicly share it.

The plugin uses the illuminate/collection package. There seems to be a dependency issue.

**Comment by skoften** [comment]
PHP 7.4.12

I've emailed you the composer.json, thanks!

**Comment by jakubjo** [comment]
Can you send the file directly to me at: jakub@jakub.io ?

**Comment by skoften** [comment]
Done!

**Comment by jakubjo** [comment]
I've removed the `illuminate/collections` dependency. The update is also available through the plugin store. 
Please try installing it again. You can reopen this issue or create additional ones if you encounter new issues.
Hope you'll enjoy the plugin!
