### ISSUE TITLE
Can this be done in any way..

### ISSUE THREAD

**Issue by wmdhosting** [alpshq/craft-share-previews#5]
This is nice idea. :)

Is it posiblle  let say to  add  twig path to twig template  to show that template or part template in preview.. 

I use images now..   but will be much better  if i can show same way its shown on frontend..
![2021-12-22_13-42-32](https://user-images.githubusercontent.com/76176291/147094565-99a02443-3ec2-42fe-9e3d-419c769c856e.png)

**Comment by jakubjo** [comment]
Unfortunately it can't render a template to an image. 
You could do that with [spatie/browsershot](https://github.com/spatie/browsershot) for example. But than you'd also need node running on the server. 
The plugin is meant as an alternative where you solely have PHP only.

You can of course recreate the images you've posted using the plugin. 
Look at the example image below which was created using the plugin. It goes into a similar direction: Recreating an UI.

![t-rMzuhen22B3wlWVOcgU-3kiwOHVLSIGDjYmhP1WQqkBiD_POMBQuSF5Nk4bxxln-nIlGmOIyZEaQ30GuyFwkFtxn-xzNK9aoFT7f7pimfw](https://user-images.githubusercontent.com/2873852/147408497-9a59d29f-604b-47c6-98c2-7de36fa0393c.png)

**Comment by jakubjo** [comment]
@wmdhosting 

Do you need any further guidance?

**Comment by wmdhosting** [comment]
Thx..  you can close this one..
