### ISSUE TITLE
More flexible asset picker

### ISSUE THREAD

**Issue by andypullen** [alpshq/craft-share-previews#6]
I would love to be able to conditionally select an asset beyond what is associated with the entry. For example, if I have a Structure where the entry doesn't have an `image` set, but its parent does, I want to be able to select the parents' image— something like `{{ entry.image ?? entry.parent.image }}`

**Comment by jakubjo** [comment]
Hi @andypullen,

there's actually a `parent` property on elements: https://docs.craftcms.com/api/v3/craft-base-element.html#public-properties

So `{{ entry.image ?? entry.parent.image }}` should work -- did you try and it did not worked out?

**Comment by andypullen** [comment]
![CleanShot 2022-02-02 at 12 06 45@2x](https://user-images.githubusercontent.com/9940032/152229096-c7b1a6bf-f581-46e9-9c76-a316e3c098c4.jpg)
Unless I'm not seeing something, there isn't a way to enter code for image assets at all. Could I be overlooking it?

**Comment by jakubjo** [comment]
Yeah, you're right, @andypullen! Thanks to bringing this to my attention. I somehow missed the context.

I'll add a field to the asset layer where you'd be able to write in a Twig expression as [mentioned earlier](https://github.com/alpshq/craft-share-previews/issues/6#issuecomment-1014682278) -- I assume this would help in your case?

**Comment by jakubjo** [comment]
@andypullen 

You should be able to upgrade to 1.6.0 which includes the more flexible asset picker based on twig expression.

Your expression will likely look something like `{{ entry.image.one().id ?? entry.parent.image.one().id }}`.
Review the [corresponding PR](https://github.com/alpshq/craft-share-previews/pull/8) to view a screenshot of the new feature.

Let know if this suits your needs!

**Comment by andypullen** [comment]
It would indeed! Thank you :)
